### ISSUE TITLE
Include yarn or npm compatible package.json

### ISSUE THREAD

**Issue by serv** [regosen/Gapless-5#17]
I was wondering if we could consider adding npm or yarn compatible `package.json` to allow people to use yarn or npm to manage the module.

**Comment by francoiscabrol** [comment]
yes please!

**Comment by regosen** [comment]
I finally took a stab at this, but I'm finding that it requires more than just a package.json to work in a node.js environment.  If I attempt to use Gapless5 from node.js, the following are not defined:
- window
- document
- Audio
- XMLHttpRequest
- navigator (for user-agent, due to minor style differences in macOS)

We could theoretically pass in all these things via the Gapless5 constructor (and expect the caller to provide these via modules like JSDOM, etc.) but I'm not sure if that's what you'd want.  Please advise.

**Comment by serv** [comment]
Sorry I wasn't clear about the request. I agree that making this package to work in Node.js wouldn't be easy. I wasn't asking about that. I am happy about this package working only in the browser.

Instead, I was wondering if this package had a package.json file which allows itself work with NPM or Yarn.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json

**Comment by regosen** [comment]
Oh I see!  Well that's easy, done!

**Comment by regosen** [comment]
I've also registered the package with npm: https://www.npmjs.com/package/@regosen/gapless-5

If this is working for you, I'll go ahead and close this issue.

**Comment by serv** [comment]
Thanks @francoiscabrol. I'll close the ticket.
