### ISSUE TITLE
Memory usage?

### ISSUE THREAD

**Issue by hdijkema** [regosen/Gapless-5#9]
I've tried gapless-5 on windows using chrome and it works ... gapless :-). 

However when I try the same on my iphone 4, after some loading time, the page abort with 'problems'.

I see memory usage of the google chrome when loading tracks increase to about 800Mb for a full CD, which is quite a lot. Also I see in my apache logs that music songs are loaded at about the same speed, the memory usage is increasing. 

Is this a feature or a bug?

**Comment by regosen** [comment]
Hi Hans.  4 days ago I merged a pull request that may have improved this greatly:

https://github.com/regosen/Gapless-5/pull/8

Let me know if you're experiencing this even with these changes.  Thanks!

**Comment by hdijkema** [comment]
I installed the master.zip, which I downloaded today. However, it doesn't work on my iphone4.

**Comment by hdijkema** [comment]
It is the memory usage. I can give you a web address (non public) for testing purposes if you want.

**Comment by regosen** [comment]
Yes, that would help, thanks!

**Comment by hdijkema** [comment]
I need your private email address for this.

Op 6-1-2016 om 16:20 schreef Rego Sen:
>
> Yes, that would help, thanks!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/regosen/Gapless-5/issues/9#issuecomment-169353632>.
>

-- 
Hans Dijkema
Weerdslag 64
7206BT Zutphen

tel. 06 4639 0827
email: hans@dykema.nl <mailto:hans@dykema.nl>

**Comment by regosen** [comment]
My email address should be visible from my GitHub profile: https://github.com/regosen.  Let me know if it doesn't appear for some reason.

**Comment by bubbleguuum** [comment]
I tried Gapless-5 embedded in a Chromecast receiver.

I was full of hope when it played the 2 Synth short samples of the demo page. perfectly gapless, with looping. 

Unfortunately when I tried to play 2 real gapless music tracks (WAV or FLAC but this doesn't matter), the Chromecast started playing the first track...then crashed after 20s or so.

I supposed this is due to the amount of memory needed, that just make it crash at some point. And this was a v2 model, supposedly with more memory.

Gapless on Chromecast is no joy it seems...

**Comment by wwoast** [comment]
I've been thinking about how to improve memory usage for Gapless. The first thing to investigate is if createMediaElementSource() loads sound into the audiocontext without decompressing the sounds. I imagine one of the reasons Gapless uses memory is that audio stays decompressed in memory when it's loaded via straight XHR.

I think the ideal strategy (bearing in mind the mobile-JS-sleep issue), is loading songs nearly one at a time for the first 2-3 tracks. Then, assuming the user won't be switching tracks or isn't in a shuffle mode, start downloading as many tracks as possible, up to a 6-7 song or 200/300MB "paging" limit. Then, as you play the Nth track at the end of the "paging buffer", reclaim all N-1 tracks and load the next N-1 tracks.

**Comment by wwoast** [comment]
Testing Gapless on Chromecast today for a playlist of 30+ tracks on my home LAN and it's working extremely well, without pops or noise. I also notice Chromecast displays the mouse pointer on your TV now -- so I suspect this is just Chromecast improvements.

**Comment by bubbleguuum** [comment]
@wwoast 

Are you running a receiver on the Chromecast embedding Gapless-5 ? Last time I tried playing 2 consecutive FLAC tracks several minute each, it made de Chromecast crash a few seconds after it was attempting to load the second track in memory.

**Comment by wwoast** [comment]
Nope, this is purely through a Chrome tab running Gapless that's casted to the Chromecast. My source files were 192kbps and 320kbps MP3s in this case.

**Comment by wwoast** [comment]
I finally got my Gapless jukebox partially working on iOS / Safari, but any time the playlist is long or there's lots of songs, the Safari tab crashes. I've seen Firefox repeatedly OOM one of my older Linux laptops for larger playlists as well.

I think the solution for both network and memory resource issues is a XHR request manager. The request manager would track XHR error events and file size per song load, and queue any XHR.send() events so that the AudioContext.buffer doesn't grow too large. An important feature would be policies -- i.e. for phones, keep the AudioContext.buffer window limited to one song before, and N songs in front of the currently-playing track.

Sadly, I don't see a way yet to effectively shrink existing buffers outside of buffer-layering and cutover tricks. Doing guaranteed-gapless low-latency cutovers with buffers will likely require browsers to implement AudioWorkers. :(

**Comment by lnicola** [comment]
One aspect that changes things a bit is the introduction of FLAC support for HTML5 Audio in an upcoming Firefox version.

**Comment by wwoast** [comment]
Found an unfixed Chromium issue that likely relates to WebAudio API memory usage problems I've seen with larger playlists: https://bugs.chromium.org/p/chromium/issues/detail?id=576484

The wwoast@0c191e161a5527f6f89ffe51e0d0fba06bcaacd1 branch tries to manage memory usage by deleting an old audioContext and swapping new ones. This branch tries to swap contexts when moving between shuffled/unshuffled modes. Unfortunately testing has shown this approach doesn't work -- browsers silently count the number of audioContexts made and have an upper limit on how many are permitted per tab.

It feels like fixing WebAudio memory usage will require working with browser devs.

**Comment by acroyear** [comment]
I wonder if these problems still persist given that we're 5 years on and at least 1 generation improved in the chromecast device (and multiple generations improved in the Chromecast o/s).

**Comment by hdijkema** [comment]
I've got no idea. Maybe...

**Comment by regosen** [comment]
I just added native support for limiting how many tracks are loaded at one time.

If you're still encountering memory issues, please upgrade Gapless-5 to 1.1.0 and try setting `loadLimit` to 2 in your `Gapless5` constructor.  See README for examples and details.
